### ISSUE TITLE
Does this work with Arduino Uno also ?

### ISSUE THREAD

**Issue by stefania11** [adafruit/FifteenStep#1] opened 2016-01-11 04:46 UTC

**Comment by toddtreece** [comment] 2016-01-11 04:52
Yep. It should work on the Uno, and you can check out the included [basic example](https://github.com/adafruit/FifteenStep/blob/master/examples/basic/basic.ino) that uses the [Arduino MIDI library](https://github.com/FortySevenEffects/arduino_midi_library) for serial MIDI out. Let me know if you have questions.

**Comment by stefania11** [comment] 2016-01-11 05:00
Thank you for the prompt reply Todd! It seams to always get stuck on upload
(see screenshot attached).

I installed all libraries and followed steps from here, restarted Arduino,
reset the board, not sure what I am doing wrong :S

Stefania Druga - Founder

+1 415 503 89 44

---

HacKIDemia: Inspire the kids to imagine a better tomorrow

and give them the tools to build it!

Web http://www.hackidemia.com/| Facebook
https://www.facebook.com/Hackidemia| Twitter
https://twitter.com/HacKidemia| YouTube
http://www.youtube.com/user/HacKIDemia| Newsletter http://bit.ly/ZrvxtF|

**Comment by toddtreece** [comment] 2016-01-11 05:03
@stefania11 the screenshot is missing from the reply. try uploading it via the GitHub issue UI. i don't think email attachments will show up on GitHub.

**Comment by stefania11** [comment] 2016-01-11 05:04
<img width="504" alt="screen shot 2016-01-10 at 11 58 38 pm" src="https://cloud.githubusercontent.com/assets/1336419/12227222/d1edfcee-b7f6-11e5-9cea-77b66fe0841c.png">

**Comment by stefania11** [comment] 2016-01-11 05:10
- full error message 
  Sketch uses 4,888 bytes (15%) of program storage space. Maximum is 32,256 bytes.
  Global variables use 227 bytes (11%) of dynamic memory, leaving 1,821 bytes for local variables. Maximum is 2,048 bytes.
  avrdude: stk500_recv(): programmer is not responding
  avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
  avrdude: stk500_recv(): programmer is not responding
  avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
  avrdude: stk500_recv(): programmer is not responding
  avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
  avrdude: stk500_recv(): programmer is not responding
  avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
  avrdude: stk500_recv(): programmer is not responding
  avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00

**Comment by toddtreece** [comment] 2016-01-11 05:15
@stefania11 can you upload anything else to your board (like the blink example)? if not, check this out for possible solutions: http://www.instructables.com/id/A-solution-to-avrdude-stk500getsync-not-in-syn/

closing this one out since it looks like it's not a bug with this library. we try to use github issues for software bug & enhancements, but if you need general help getting this working, please post questions in our customer support forums and we would be happy to help : http://forums.adafruit.com/

**Closed as completed by toddtreece** 2016-01-11 05:15 UTC
